import React from 'react';
import { Link } from 'react-router-dom';
const ServerImage1 = '/assets/images/ServerStorage.png';
const ServerImage2 = '/assets/images/server-image-2.webp';
const Vast1 = '/assets/images/vast-1.webp';
const Vast2 = '/assets/images/vast-2.webp';
const Vast3 = '/assets/images/vast-3.webp';
const Vast4 = '/assets/images/vast4.webp';
const Vast5 = '/assets/images/vast-5.webp';
const Vast6 = '/assets/images/vast-6.webp';
const SysLog1 = '/assets/images/sys-log-1.webp';
const SysLogo2 = '/assets/images/sys-logo-2.webp';
const SysLogo3 = '/assets/images/sys-logo-3.webp';
const SysLogo4 = '/assets/images/sys-logo-4.webp';
const SysLogo5 = '/assets/images/sys-logo-5.webp';
const SysLogo6 = '/assets/images/sys-logo-6.webp';
const SysLogo7 = '/assets/images/sys-logo-7.webp';
const Rectangle27 = '/assets/images/Rectangle-27.webp';

const ServerStorage = () => {
  return (
    <main>
      {/* Full-width Banner Image */}
      <div className="banner-full-image">
        <img src={ServerImage1} alt="Server & Storage Banner" className="banner-img" />
      </div>

      {/* Banner styles */}
      <style dangerouslySetInnerHTML={{
        __html: `
          .banner-full-image {
            width: 100%;
            overflow: hidden;
          }

          .banner-img {
            width: 100%;
            display: block;
          }
        `
      }} />

      {/* Content Section */}
      <div className="container">
        <div className="row align-items-center my-5">
          <div className="col-12 col-lg-7" style={{textAlign:'justify'}}>
            <p style={{ color: '#686D76', fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Open Sans\', \'Helvetica Neue\', sans-serif' }}>The volume of data generated by expanding businesses increases exponentially. Effectively managing this data becomes a complex and difficult undertaking when choosing the appropriate resources, storage, and backup options. We at JK Global IT Solutions are available to help you set up a reliable server and storage system. With a cost-effective strategy, we help you get the most out of your IT expenditures by guaranteeing optimal data use, immediate accessibility, and improved security, all of which eventually improve business performance.</p>
            <p style={{ color: '#686D76', fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Open Sans\', \'Helvetica Neue\', sans-serif' }}>At JK Global IT Solutions, we provide the latest and most suitable servers and storage devices to help you tackle your challenges effectively. We stay ahead of the curve by regularly upgrading to the latest industry trends. In today's rapidly growing business environment, scalability and operational efficiency are crucial. That's why we custom-build server solutions tailored to your specific needs in terms of performance, scalability, and data capacity. Share your data processing requirements with us, so you can focus on your core business while we handle all your storage needs.</p>


            <ul style={{ listStyle: 'none', padding: 0, margin: 0, fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Open Sans\', \'Helvetica Neue\', sans-serif' }}>
              <li style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '0.5rem' }}>
                <span style={{ fontSize: '18px', background: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginTop: '2px', flexShrink: 0, lineHeight: 1 }}>○</span>
                <span style={{ color: '#686D76' }}>Latest Servers and Storage Devices</span>
              </li>
              <li style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '0.5rem' }}>
                <span style={{ fontSize: '18px', background: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginTop: '2px', flexShrink: 0, lineHeight: 1 }}>○</span>
                <span style={{ color: '#686D76' }}>Custom-Built Solutions</span>
              </li>
              <li style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '0.5rem' }}>
                <span style={{ fontSize: '18px', background: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginTop: '2px', flexShrink: 0, lineHeight: 1 }}>○</span>
                <span style={{ color: '#686D76' }}>Regular Upgrades</span>
              </li>
              <li style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '0.5rem' }}>
                <span style={{ fontSize: '18px', background: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginTop: '2px', flexShrink: 0, lineHeight: 1 }}>○</span>
                <span style={{ color: '#686D76' }}>Scalability and Operational Efficiency</span>
              </li>
              <li style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '0.5rem' }}>
                <span style={{ fontSize: '18px', background: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginTop: '2px', flexShrink: 0, lineHeight: 1 }}>○</span>
                <span style={{ color: '#686D76' }}>Focus on Core Business</span>
              </li>
            </ul>
          </div>
          <div className="col-12 col-lg-5 text-center">
            <img className="img-fluid" src={ServerImage2} alt="" />
          </div>
        </div>
      </div>
      <div className="container-fluid">
        <h2 className="text-center fw-bolder" style={{ color: '#1B8DBB' }}>Vast Selection of Storage Options</h2>
        <div style={{ gap: '50px' }} className="row container justify-content-center w-100 h-100 d-flex ms-0 ms-lg-5 mt-5">
          <div style={{ boxShadow: 'rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px' }} className="col-12 col-lg-3 p-4 text-center rounded justify-content-center align-items-center">
            <img className="img-fluid" src={Vast1} alt="" />
            <h3 style={{ color: '#1B8DBB' }} className="fw-bolder">Monitoring Platform</h3>
            <p className="text-start">This server is utilized for applications that require several "virtual" servers in order to save costs and for intensive video analytics. With Windows Server 2012R2, these U series servers include dual octa-core processors and 32GB of RAM.</p>
          </div>
          <div style={{ boxShadow: 'rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px' }} className="col-12 col-lg-3 p-4 text-center rounded align-items-center">
            <img className="img-fluid" src={Vast2} alt="" />
            <h3 style={{ color: '#1B8DBB' }} className="fw-bolder mt-4">Broadcast Server</h3>
            <p className="text-start">specialized broadcast servers to provide flawless live news performance. These servers are utilized for continuous, high-traffic operation.</p>
          </div>
          <div style={{ boxShadow: 'rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px' }} className="col-12 col-lg-3 p-4 text-center rounded align-items-center">
            <img style={{ height: '80px' }} className="img-fluid" src={Vast3} alt="" />
            <h3 style={{ color: '#1B8DBB' }} className="fw-bolder mt-3">NAS</h3>
            <p className="text-start">Data can be retrieved from a centralized, authorized network using NAS storage. NAS is the ideal option if you require a highly scalable and flexible central storage solution.</p>
          </div>
        </div>
        <div style={{ gap: '50px' }} className="row container justify-content-center w-100 h-100 d-flex ms-0 ms-lg-5 mt-5 mb-5">
          <div style={{ boxShadow: 'rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px' }} className="col-12 col-lg-3 p-4 text-center rounded align-items-center">
            <img className="img-fluid" src={Vast4} alt="" />
            <h3 style={{ color: '#1B8DBB' }} className="fw-bolder">Rackmount</h3>
            <p className="text-start">At JK Global IT Solutions, we provide rack-mounted servers that optimize space, offer easy scalability, improve airflow with advanced cooling, and simplify maintenance—making them perfect for efficient data center operations.</p>
          </div>
          <div style={{ boxShadow: 'rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px' }} className="col-12 col-lg-3 p-4 text-center rounded align-items-center">
            <img className="img-fluid" src={Vast5} alt="" />
            <h3 style={{ color: '#1B8DBB' }} className="fw-bolder">Enterprise Servers</h3>
            <p className="text-start">JK Global IT Solutions meets enterprise data storage requirements with a range of solutions, including Linux, Apache, VMWare, Windows, and more, tailored to your data center needs.</p>
          </div>
          <div style={{ boxShadow: 'rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px' }} className="col-12 col-lg-3 p-4 text-center rounded align-items-center">
            <img className="img-fluid" src={Vast6} alt="" />
            <h3 style={{ color: '#1B8DBB' }} className="fw-bolder mt-4">PowerEdge R730</h3>
            <p className="text-start">Data can be retrieved from a centralized, authorized network using NAS storage. NAS is the ideal option if you require a highly scalable and flexible central storage solution.</p>
          </div>
        </div>
      </div>

      <div className="container">
        <h1 style={{ color: '#686D76', textAlign: 'center' }}><b>Networking Solutions</b> </h1>
        <br />
        <div className="row justify-content-center gx-3">
          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/systemintegration">
              <span className="box">
                <img src={SysLog1} alt="" className="me-2" />
                <b>System Integration &Maintenance</b>
              </span>
            </Link>
          </div>
          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/infrastructure">
              <span className="box">
                <img src={SysLogo2} alt="" className="me-2" />
                <b>Infrastructure Management</b>
              </span>
            </Link>
          </div>

          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/serverstorage">
              <span style={{ backgroundColor: 'black', border: 'none' }} className="box">
                <img src={SysLogo3} alt="" className="me-2" />
                <b>Server & Storage</b>
              </span>
            </Link>
          </div>
          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/networksecurity">
              <span className="box">
                <img src={SysLogo4} alt="" className="me-2" />
                <b>Network security</b>
              </span>
            </Link>
          </div>
          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/structuredcabling">
              <span className="box">
                <img src={SysLogo5} alt="" className="me-2" />
                <b>Structured Cabling</b>
              </span>
            </Link>
          </div>
          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/cloudnative">
              <span className="box">
                <img src={SysLogo6} alt="" className="me-2" />
                <b>Cloud Native Solution</b>
              </span>
            </Link>
          </div>
          <div className="col-12 col-md-6 col-lg-4 mb-3">
            <Link style={{ textDecoration: 'none' }} to="/workplace">
              <span className="box">
                <img src={SysLogo7} alt="" className="me-2" />
                <b>Workpalce Surveillance</b>
              </span>
            </Link>
          </div>

        </div>
      </div>

      <style>
        {`
          .container.mobile-only {
            display: none;
          }
          @media (max-width: 768px) {
            .container.mobile-only {
              display: block;
            }
          }
          .box {
            display: inline-block;
            padding: 10px 20px;
            background-color: #f0ebe3;
            border: 2px solid #1B8DBB;
            border-radius: 8px;
            text-align: center;
            transition: background-color 0.3s ease;
          }
          .box:hover {
            background-color: #1B8DBB;
            color: white;
          }
        `}
      </style>
    </main>
  );
};

export default ServerStorage;
